"""
Django settings for vleaks_project project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import os                        # ← Add this line!

SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=bool)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', 
                       cast=lambda v: v.split(','))


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.humanize',  
    "blog",
    "writer",      # ← ADD THIS LINE!
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "vleaks_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",   
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages", 
            ],
        },
    },
]

WSGI_APPLICATION = "vleaks_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


# Auto-detect environment and use appropriate database
if os.environ.get('PYTHONANYWHERE_SITE'):
    # PRODUCTION: Use SQLite (free on PythonAnywhere)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',}}
    

else:
    # LOCAL DEVELOPMENT: Use MySQL (XAMPP)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': config('DB_NAME', default='vleaks'),
            'USER': config('DB_USER', default='root'),
            'PASSWORD': config('DB_PASSWORD', default=''),
            'HOST': config('DB_HOST', default='127.0.0.1'),
            'PORT': config('DB_PORT', default='3306'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Where URLs point to
STATIC_URL = "/static/"

# Where to find static files during development
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Where collectstatic puts files for production
STATIC_ROOT = BASE_DIR / 'staticfiles'


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Message tags (fix Bootstrap compatibility)
from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.ERROR: 'error',  # Keep as 'error' for our custom CSS
}

# Login URL for @login_required decorator
LOGIN_URL = 'writer_login'  # ← ADD THIS!





# ============================================
# HTTPS / SSL SECURITY SETTINGS
# ============================================
# Only enable these in production!
if not DEBUG:
    # Redirect all HTTP requests to HTTPS
    SECURE_SSL_REDIRECT = True
    
    # Tell Django we're behind a proxy (PythonAnywhere)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Use secure cookies (HTTPS only)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # Enable HSTS (tell browsers to always use HTTPS)
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True



# ============================================
# SECURITY HEADERS
# ============================================
if not DEBUG:
    # Prevent clickjacking (don't allow site in iframes)
    X_FRAME_OPTIONS = 'DENY'
    
    # Prevent MIME-type sniffing
    SECURE_CONTENT_TYPE_NOSNIFF = True
    
    # Enable browser XSS filter
    SECURE_BROWSER_XSS_FILTER = True



# ============================================
# COOKIE SECURITY
# ============================================
if not DEBUG:
    # Session cookies
    SESSION_COOKIE_SECURE = True      # Only send over HTTPS
    SESSION_COOKIE_HTTPONLY = True    # JavaScript can't access
    SESSION_COOKIE_SAMESITE = 'Lax'   # Prevent CSRF via cookies
    
    # CSRF cookies
    CSRF_COOKIE_SECURE = True         # Only send over HTTPS
    CSRF_COOKIE_HTTPONLY = True       # JavaScript can't access
    CSRF_COOKIE_SAMESITE = 'Lax'      # Prevent CSRF




