# Generated by Django 6.0.1 on 2026-02-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="recommended",
            field=models.BooleanField(default=False),
        ),
    ]





    




